### ISSUE TITLE
Decide and document dependency update policy

### ISSUE THREAD

**Issue by Pezmc** [flowforge/handbook#125]
It looks like there are quite a few outdated dependencies across the various flowforge repositories. There's not a clear policy on how we should (proactively) handle this, and right now is usually done when we're nearing a release.

There's a balance to be found between ensuring we're not falling behind (so we can easily handle security advisories or access a new feature), and spending excess time updating dependencies.

Some possible ideas:
 - Security issues only
 - Update to the latest patch/minor, skipping major versions
 - Regular (say quarterly) updates of all dependencies

Additionally, we should consider setting up automation of the updated update policy via tools like [Dependabot](https://dependabot.com/), next-update or similar; to avoid introducing unnecessary leg work.

**Comment by ZJvandeWeg** [comment]
Introduced dependabot this release
