### ISSUE TITLE
Document how to add a new repo to the release automation

### ISSUE THREAD

**Issue by knolleary** [flowforge/handbook#79]
### Description

When adding a new repo that needs to be included in releases there are a number of tasks needed to be completed - none of which are currently documented.

 - Add `.github/workflows/release-publish.yml` to the repo - copied from one of the other repos, updated with any specific tasks needed to be run
 - Add repo to the lists in:
    - https://github.com/flowforge/admin/blob/main/checkout-release
    - https://github.com/flowforge/admin/blob/48afe2326c221416ac1c18d327cae446706d0a15/prepare-release#L46
 - *Something* to do with the `NPM_PUBLISH_TOKEN` - but I'm not sure what right now (which is why this is an issue, rather than a PR whilst I gather the info needed)

**Comment by knolleary** [comment]
@hardillb I suspect you have the missing info about `NPM_PUBLISH_TOKEN` - can I get you to take a look at this once 0.6 is done?

**Comment by hardillb** [comment]
Closing this as the `--access public` was added to the automation and the NPM_PUBLISH_TOKEN is org wide
